# Generated by Django 4.0.7 on 2024-12-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staffID', models.CharField(max_length=255)),
                ('phonenumber', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('userstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
