# Generated by Django 4.0.7 on 2024-12-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='usertype',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
