# Generated by Django 5.1.5 on 2025-02-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_billing_page_productdetails_mrp_productdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_id',
            field=models.CharField(max_length=6),
        ),
    ]
