# Generated by Django 5.1.5 on 2025-02-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productdetails_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='weight',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
