# Generated by Django 5.1.5 on 2025-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productdetails_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('original_price', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('total_item', models.CharField(max_length=255)),
                ('sub_total', models.CharField(max_length=255)),
                ('total_tax', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('billing_id', models.CharField(max_length=255)),
            ],
        ),
    ]
