# Generated by Django 5.1.5 on 2025-02-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_billing_page_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_product',
            name='pro_id',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
