# Generated by Django 5.1.5 on 2025-02-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_billing_product_pro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
